spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_spring_boot_java?useTimezone=true&serverTimezone=America/Sao_Paulo&useSSL=false
    username: root
    password: Dev@1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
